title: "AC Service & Parts | Farm Machinery & Parts Supplier"
email: ant@acparts.com.au
phone: "03 5233 1085"
mobile: "0417 319 276"
fax: "03 5233 1196"
address: "495 Larpent Road, Colac, VIC 3249"
description: >
  AC Service & Parts specializes in quality new and second-hand farm machinery, parts and equipment
  for irrigation, tractors, slurry tanks, and other agricultural needs throughout Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acparts.com.au" # production site URL
author: "Anthony Campbell"
logo: "/assets/images/logo.png"

# SEO settings
lang: en-AU
locale: en_AU
seo:
  keywords: "farm machinery, tractor parts, irrigation equipment, agricultural supplies, vacuum pumps, hydraulic parts, Pearson loader parts, slurry tanks, farm equipment Victoria"

# Contentful
contentful:
  spaces:
    - acparts:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - node_modules
  - .sass-cache
